steps:
  # Debug step
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Debug: DOPPLER_TOKEN available: ${_DOPPLER_TOKEN:0:5}..."
    secretEnv: ["_DOPPLER_TOKEN"]

  # Build step with correct secret handling
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker build \
          --build-arg "DOPPLER_TOKEN=$$_DOPPLER_TOKEN" \
          --build-arg "ENVIRONMENT=$$_ENVIRONMENT" \
          -t gcr.io/pin-mastery/f3-nextjs \
          -f apps/nextjs/Dockerfile \
          .
    secretEnv: ["_DOPPLER_TOKEN"]

  # Push step
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/pin-mastery/f3-nextjs"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "f3-2" # Name for your Cloud Run service
      - "--image"
      - "gcr.io/pin-mastery/f3-nextjs" # The image you built
      - "--region"
      - "us-central1" # e.g., us-central1
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

  # Final notification step - only runs if previous steps succeed
  - name: "gcr.io/cloud-builders/gcloud"
    id: "notify-success"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud pubsub topics publish projects/pin-mastery/topics/map-build-success \
          --message="Build succeeded for $_ENVIRONMENT deployment" \
          --attribute=environment=$_ENVIRONMENT,service=f3-2,status=success,buildId=$BUILD_ID
        echo "Success notification sent to Pub/Sub"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/233824588998/secrets/DOPPLER_TOKEN/versions/latest
      env: "_DOPPLER_TOKEN"

# Default values for substitutions
substitutions:
  _ENVIRONMENT: "production" # Default to production if not specified
