import {
  attendance,
  attendanceTypes,
  authAccounts,
  authSessions,
  authVerificationTokens,
  events,
  eventsXEventTypes,
  eventTags,
  eventTypes,
  locations,
  orgs,
  permissions,
  roles,
  rolesXPermissions,
  rolesXUsersXOrg,
  slackUsers,
  updateRequests,
  users,
} from "../drizzle/schema";

export const schema = {
  attendance,
  attendanceTypes,
  authAccounts,
  authSessions,
  authVerificationTokens,
  events,
  eventTags,
  eventTypes,
  eventsXEventTypes,
  locations,
  orgs,
  permissions,
  roles,
  rolesXPermissions,
  rolesXUsersXOrg,
  slackUsers,
  updateRequests,
  users,
};

export * from "drizzle-orm";
