import { COUNTRIES } from "./countries";

const SHOWN_NAMES: (typeof COUNTRIES)["features"][number]["properties"]["NAME"][] =
  [
    "Australia",
    "Brazil",
    "Canada",
    "Germany",
    // "Hong Kong",
    "India",
    "Indonesia",
    "Italy",
    "Japan",
    "Jordan",
    "Kenya",
    "Morocco",
    "South Korea",
    "Switzerland",
    "Thailand",
    "Uganda",
    "United Kingdom",
    "France",
    "Netherlands",
    // Need other states
    "Alaska",
    "Alabama",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District_of_Columbia",
    "Florida",
    "Georgia",
    // "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    // "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New_Hampshire",
    "New_Jersey",
    "New_Mexico",
    "New_York",
    "North_Carolina",
    "North_Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode_Island",
    "South_Carolina",
    "South_Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West_Virginia",
    "Wisconsin",
    "Wyoming",
    // "Puerto_Rico",
  ];

export const VISIBLE_COUNTRIES = {
  ...COUNTRIES,
  features: COUNTRIES.features.filter((feature) => {
    return SHOWN_NAMES.includes(feature.properties.NAME);
  }),
};
