name: Version Bump Checks

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - staging

jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check versions bumped
        uses: High-Country-Dev/version-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
